### ISSUE TITLE
Network Representation of Force Distribution 

### ISSUE THREAD

**Issue by KhushSingh** [HITS-MBM/gromacs-fda#12]
Hi, Bernd!

I conducted (TR)FD analysis to investigate the effect of a mutation on the force propagation within a protein-ligand complex. Now, I need to generate images for my publication highlighting the difference in the force distribution from the point of mutation between wild-type and mutant protein. I was hoping to generate a network representation of the force distribution within the protein, a figure similar to the one attached, Fig 2 (C). My figure looks very different (attached); the image was generated using .pfa and pf_draw package within VMD 1.9.1 as suggested in the [manual](https://github.com/HITS-MBM/fda-archive/blob/master/PF2-manual_20120829.pdf).

It would be of great help if you could advise me on how to obtain network representation of force distribution from a particular residue. 

![figure c_fda](https://cloud.githubusercontent.com/assets/22648469/25307450/c261e5a2-2766-11e7-98bb-6bd05094c18e.jpg)

![trfda](https://cloud.githubusercontent.com/assets/22648469/25307482/49011b78-2767-11e7-85ca-c45a975a935d.png)

**Comment by BerndDoser** [comment]
Hi KhushSingh,

Please take a look to the analysis modules in the documentation chapter 5. Fig 2(C) looks to me like such a graph.

Best regards,
Bernd

**Comment by BerndDoser** [comment]
Please reopen the issue or create a new one in case of more questions.
