### ISSUE TITLE
file INSTALL cannot find   ".../fda-08232016/bin/gmx".

### ISSUE THREAD

**Issue by dbiner01** [HITS-MBM/gromacs-fda#2]
When we get to the make install of the FDA patch we get an error:

-- Up-to-date: /N/u/dbiner/BigRed2/software/gromacs/fda-08232016/include/gromacs/trajectoryanalysis/analysismodule.h
-- Up-to-date: /N/u/dbiner/BigRed2/software/gromacs/fda-08232016/include/gromacs/trajectoryanalysis/analysissettings.h
-- Up-to-date: /N/u/dbiner/BigRed2/software/gromacs/fda-08232016/include/gromacs/trajectoryanalysis/cmdlinerunner.h
CMake Error at src/programs/cmake_install.cmake:42 (file):
  file INSTALL cannot find
  "/N/u/dbiner/BigRed2/software/gromacs/fda-08232016/bin/gmx".
Call Stack (most recent call first):
  src/cmake_install.cmake:40 (include)
  cmake_install.cmake:48 (include)

make: *** [install] Error 1

Any suggestions?

Also, is the FDA patch supposed to be installed in the GROMACS install directory?

Thanks for all your help!

Dan

**Comment by BerndDoser** [comment]
Please use the installation procedure described at [fda-manual](https://github.com/HITS-MBM/gromacs-fda/blob/fda/fda-manual/fda-manual.pdf). Using '-DGMX_BINARY_SUFFIX=_fda' there should be an executable 'gmx_fda' instead of 'gmx'. It would also recommended to compile out of the source directory.

**Comment by dbiner01** [comment]
There was a small typo in my cmake command.  Thanks for getting back to me so quickly!
