### ISSUE TITLE
ndx for fda_graph?

### ISSUE THREAD

**Issue by fluver** [HITS-MBM/gromacs-fda#22]
Im currently trying to investigate my protein using the latest gmx_fda version but struggle with fda_graph.
Running `gmx_fda mdrun -nt 1 -rerun system.cat.xtc -s ../../topol.tpr -pfn index.ndx -pfi input.pfi` works fine. But `echo Protein | gmx_fda fda_graph -i fda.pfr -s ../../topol.tpr -n index.ndx` fails with 

> Fatal error:
> Number of atoms in group 21792 does not match number of FDA points 37812.
> 
(Protein group has 21792 elements)
37812 corresponds to the total number of residues in my system, including ions and water.
From the manual i concluded that only residues in the Protein group should have been considered, i also included `energy_grp_exclusion = yes` in my input file but that didn't changed the number of FDA points.

Question is: How to construct a proper index file for fda_graph?

input.pfi:
```
onepair = summed
group1 = Protein
group2 = Protein
type = all
atombased = no
residuebased = pairwise_forces_scalar
```

**Comment by BerndDoser** [comment]
It should work as you told. The feature is tested within the unit tests. Was your test run error-free?
The unit test is located at src/gromacs/gmxana/fda/tests/data/glycine_trimer. You can run it with
```
echo C-alpha | gmx_fda fda_graph -i fda.pfr -s glycine_trimer.pdb -f traj.trr -n index.ndx -frame all -pymol result.pml
```
The pfr-file was created with
```
onepair = summed
group1 = System
group2 = System
atombased = pairwise_forces_vector
residuebased = no
type = all
energy_grp_exclusion = yes
```
If this works correctly, please provide me your system, so that I can reproduce the error.

**Comment by BerndDoser** [comment]
Please reopen if the issue still exist.
