### ISSUE TITLE
FDA for coarse-grained models

### ISSUE THREAD

**Issue by MohaddesehPeyro** [HITS-MBM/gromacs-fda#25]
Hi,
I was wondering if it is possible to use FDA for a one-bead-per-amino-acid coarse-grained molecular dynamics model that runs on Gromacs. I have tried to run it but I get empty output files. In the model that I use, only residues are taken into account and the interactions are defined between residues, so I have no atomic information in the input files that I use for FDA. 
Thanks in advance,
Mohaddeseh

**Comment by BerndDoser** [comment]
Hi Mohaddeseh,

thanks for your interesting question! Unfortunately, I have never tried to run coarse-grained molecular dynamics in GROMACS. Which force field you are using? Maybe Martini? I assume that GROMACS is not using the same path for the coarse-grain interactions as for the atomic ones. If you could send me a small example input, which I can easily run with GROMACS, I can take a look via debugging mode which path will be chosen and if there is any possibility to extract the force distributions via FDA.

Best regards,
Bernd

**Comment by MohaddesehPeyro** [comment]
Hi Bernd,

Thanks for your response and sorry for my delayed answer.
The force field is not Martini, it is a force field developed by our collaborator. Great, thanks for offering to run FDA with my input files. I will send them to you via email. Is that OK? 

Best,
Mohaddeseh

**Comment by BerndDoser** [comment]
I would try to use atombased instead of residuebased FDA. When I understand your input files correctly, then each entry in `conf.gro` corresponds to an amino acid or to a group of atoms in general. Therefore, atoms are already residues in your case.

**Comment by MohaddesehPeyro** [comment]
Wonderful idea! I tried it and it worked and I got results. Now I'm about to analyze the results. Thanks so much for your help. I'll let you know if I have any other issues.
