### ISSUE TITLE
Are velocities needed in your trajectory file?

### ISSUE THREAD

**Issue by dbiner01** [HITS-MBM/gromacs-fda#3]
I have output .xtc files for my simulations and I get an error saying their are no velocities.  Do I have to run the simulation again writing out velocities or will the FDA work regardless of the error?

Thanks,
Daniel

**Comment by dbiner01** [comment]
Also, when I try to map the force network with fda_graph, I can only get it to work with a pfa file.  When I try it with a pfr, the pfr ends up having one more residue than the c-alpha option in my index file and this mismatch causes a fatal error.  Is there a way to get around this?

**Comment by BerndDoser** [comment]
Hi Daniel,

thanks for your report! Could you please provide us the corresponding input files and commands for your issue.

Best regards,
Bernd

**Comment by bcostescu** [comment]
​Only coordinates (as found in the .xtc files) are required, as forces​ are
calculated based on the relative positions of atoms with respect to each
other.

Where do you get the error saying that there are no velocities and what is
the exact error messages?

Cheers,
Bogdan

**Comment by BerndDoser** [comment]
Please reopen it if there is still an issue.
