### ISSUE TITLE
Questions about visualization with VMD

### ISSUE THREAD

**Issue by willwzhang** [HITS-MBM/gromacs-fda#30]
Hi Bernd,

I'm a little confused about the VMD visualization plugins. Is this the website to download the latest version of  pf2 VMD plugins?
https://github.com/HITS-MBM/fda-archive

When using
vmd-plugins_pf2_20120829.tar.gz
and importing
```
package require pf_loaduser
pf_loaduser <filename.pfr>
```
in VMD, I got the following error,
expected floating-point number but got "pairwise_forces_scalar".
Seems it could not read the phrases like
"pairwise_forces_scalar
frame 0"
from my .pfr file. Only when I delete these lines manually, it can work.
Is this normal or I did something wrong?
Thanks!

Wen

**Comment by BerndDoser** [comment]
I am waiting for a response of the developer of the VMD plugins. To my present knowledge the VMD plugins are deprecated and were replaced by the gmx analysis modules.

**Comment by BerndDoser** [comment]
I will reactivate the VMD plugins, because of the more flexible usage. Although the gmx analysis module 'fda_graph' is easier to use, it is very limited to handle more complex force networks by using the pdb format.

**Comment by willwzhang** [comment]
> I will reactivate the VMD plugins, because of the more flexible usage. Although the gmx analysis module 'fda_graph' is easier to use, it is very limited to handle more complex force networks by using the pdb format.

Thanks a lot. I've also tried fda_graph to generate a PDB file. But it seems the PDB file don't have the sequence information, and only generate a network structure. May I know how should I overlap that to my original protein structure?

**Comment by BerndDoser** [comment]
Yes, the pdb file produced by fda_graph contains only the network information. With VMD you can load the structure or the trajectory as second input. Using the flag '-pymol' a pml file will generated which can be loaded with Pymol.

**Comment by willwzhang** [comment]
> Yes, the pdb file produced by fda_graph contains only the network information. With VMD you can load the structure or the trajectory as second input. Using the flag '-pymol' a pml file will generated which can be loaded with Pymol.

When I load the structure or trajectory into the pdb with VMD, always get errors:
ERROR> Mismatch between existing molecule or structure file atom count and coordinate or trajectory file atom count. 
It seems the number of atoms in the pdb file from fda_graph is neither the number of protein atoms nor system atoms from the original structure. 
My .pfi file:
```
onepair = summed
group1 = Protein
group2 = Protein
atombased = no
residuebased = pairwise_forces_scalar
type = all
time_averages_period = 0
```
and running fda_graph as:
```
gmx_fda fda_graph -i example.pfr -s example.gro -f example.trr -n example.ndx -o example.pdb
```
selecting group 3 (C-alpha) for residue model points (the only one can match).

**Comment by BerndDoser** [comment]
You have to load it as two separate molecules:
1. The example.gro file for the atomic structure. The gro-file contains the reoriented coordinates.
2. Load example.pdb as new molecule (not into the first structure)

If you are using '-frame skip <n>' you have to generate a suitable trajectory, which has the same frames.

**Comment by willwzhang** [comment]
Sorry, what I mean is actually something like Fig. 2B in doi: 10.1186/1471-2105-12-101. So the Fig. 2B is actually by VMD plugins?
And since the deprecated VMD plugins, can I take the summation of the absolute values of scalar_force column in .pfa file for each atom as the force on atom? (or in .pfr file for each residue, is this the same as the equation(3) in the paper?)

**Comment by BerndDoser** [comment]
The publication you mentioned was before I was working on FDA, but I would also say that it was produced with the VMD plugins. The fda_graph is only for the network graphs. Therefore, I would like to ask you for some patience. I will provide the VMD plugins in the next days.

**Comment by willwzhang** [comment]
Thanks a lot!

**Comment by BerndDoser** [comment]
Please find the VMD plugins in the new repository https://github.com/HITS-MBM/gromacs-fda-vmd
