### ISSUE TITLE
Merge with GROMACS 2020

### ISSUE THREAD

**Issue by BerndDoser** [HITS-MBM/gromacs-fda#31]
Annual merge to the next major version.

**Comment by BeastyBlacksmith** [comment]
Do you have an estimate on when this will happen?
I am planning to build upon this, but would like to wait for the merge if it is coming soon and I can't build the current version due to linking errors with openMP.
If there is anything I can help with, let me know.

**Comment by BerndDoser** [comment]
The merge basically finished. I only have to organize the unit tests. I hope that I can release it in next days. Knowing that you are waiting for it let me hurry up.

With which version do you have linking issues?

**Comment by BeastyBlacksmith** [comment]
Thats gromacs 2019.3. I worked around it by disabling the OpenMP variable in the cmake-file. Building gromacs 2020.3 works fine.

Besides this, since what you have done here is similar to what we want to build I would be happy to have a chat about your experiences, if time permits.

**Comment by BerndDoser** [comment]
Do you have the OpenMP issue only for GROMACS-FDA or also for the unchanged GROMACS version?

Of course, chat is possible. Would tomorrow morning around 10 a.m. be suitable for you?

**Comment by BeastyBlacksmith** [comment]
I have the issue also for the unchanged GROMACS version, nothing on your end.

If possible, I would prefer early afternoon around 1 p.m..

**Comment by BerndDoser** [comment]
Great! Then let us fix tomorrow 1:30 p.m. I will send my contact data via mail.

**Comment by Ecaloota** [comment]
I am also keen on using the GROMACS 2020.1 merge.

**Comment by BerndDoser** [comment]
It's almost finished and will be released this week.

**Comment by BeastyBlacksmith** [comment]
Thanks for the release! Can you tell me which gromacs version you merged with ( or the commit SHA? )

**Comment by BerndDoser** [comment]
The merge with GROMACS v2020 (29dff396) is finished, but for the fda-2.10 release I still need the last bugfix #28.
