### ISSUE TITLE
Issues visualising PFR output - renumbering issue? and seg fault with v.2.10 and GROMACS 2020.1

### ISSUE THREAD

**Issue by Ecaloota** [HITS-MBM/gromacs-fda#36]
Hi @BerndDoser 

I've used gmx_fda V 2.10 for GROMACS 2020.1 to generate a PFR file using the following command:

`gmx_fda mdrun -nt 1 -rerun r1pr_3fcs_2d_skip10.xtc -pfi input.pfi -pfr out_test.pfr -s r1pr_3fcs_2d.tpr -pfn index.ndx`

Where the input.pfi file contains the following parameters:

> onepair = summed
> group1 = Protein
> group2 = Protein
> residuebased = pairwise_forces_scalar
> type = all
> time_averages_period = 10

This outputs the expected PFR file, and it resembles those provided in your gromacs-fda-vmd repository alagly examples. However, I can't visualise this output; I've tried the VMD scripts, following the examples on pages 16 and 17 of the FDA manual, and using fda_graph to convert the PFR file to a pymol file or a PDB. 

The former looks like it works throughout (i.e. the TCL console prints out "now loading inter-residue pairwise forces" and a pf_minmax value) but neither the `pf_draw` or `trace variable vmd_frame(0) w pf_draw` commands appear to output the expected cylinders. I can get the correct output for the residue-based alagly example from the previously mentioned repository, with the cylinders.

Also, when I try and run:
`gmx_fda fda_graph -i out_test.pfr -s r1pr_3fcs_2d.tpr -f r1pr_3fcs_2d_skip10.xtc -n index.ndx -o fda_graph_output_test.pdb -pymol fda_graph_output_test_pymol_traj.pml`

I get an error that the "Number of atoms in group 292 does not match the number of FDA points 294". From my NDX file, I know that the protein is comprised of 292 C-alpha's, so I assume that the cause of the mis-numbering is due to residue renumbering by gmx_fda? If true, unfortunately when I turn off residue renumbering, I get a SegFault 11 immediately after the notification that "Residue number collision detected, residues will NOT be renumbered", so I can't test this.

Any help would be greatly appreciated; I'm happy to send you any of the input and output files privately if that helps.

**Comment by Ecaloota** [comment]
Ping @BerndDoser

**Comment by BerndDoser** [comment]
@Ecaloota, I am on vaccation and will be back next week.

**Comment by Ecaloota** [comment]
No worries, thanks.

**Comment by BerndDoser** [comment]
Hi @Ecaloota. You have closed this issue. Is it resolved?

**Comment by Ecaloota** [comment]
Hi @BerndDoser. Partly, though I've written a few scripts to work around some of the issues, so I can visualise output now with a few extra little steps.

For some reason, forces were being calculated between C-alphas of my protein and a calcium ion in my system, which was responsible for the mismatch between the number of force-pairs expected by gmx_fda and by the input .NDX file. I expect this is either because the Ca ion was part of the system definition in my ITP files, or because gmx_fda is searching for CA atoms and incorrectly picking up the Ca ion along with the protein C-alphas?

After removing the force-pairs associated with that atom, I can visualise in VMD easily enough. I was making the mistake of not inputting "true" in my pf_read command for the residue renumbering (i.e. I was typing `pf_read "myfile.pfr"` instead of `pf_read "myfile.pfr" "true"`).

However, when outputting to a PDB for visualisation with Pymol, I encountered another issue where the trajectory.pdb file that is output has coordinate units of nm, whereas the network.pdb file with the CONECT headers is output in units of Angstroms (the latter is probably the correct behaviour given the definition of the PDB file?). Not sure where this issue comes from, other than the fact that the .gro file is originally in nm and likely isn't being converted into Angstroms when the conversion to a PDB file is being done.

Thanks!

Edit: Oh, and unfortunately I don't have any insight into the seg fault 11 issue, but that's no longer an issue with my system.

**Comment by BerndDoser** [comment]
Thank you @Ecaloota for the detailed report. There was an issue with an pointless check of fda points (#34) fixed in the 2019 branch. Unfortunately, I have forgotten to merge the latest commits of the 2019 into the 2020 branch before deploying FDA 2.10.
I will catch up and release it in version 2.10.1.
