### ISSUE TITLE
LINC warnings while running (TR)FDA

### ISSUE THREAD

**Issue by KhushSingh** [HITS-MBM/gromacs-fda#4]
Hi,

I am trying to rerun my trajectory to recompute the atomic forces using (TR)FDA. After running for a while, my job stops due to an error (pasted below). I am not sure if this is related, but while generating my tpr file, I did not get any LINC warnings. It would be of great help if you could guide me as to what could lead to such error.

**Program mdrun_pf2, VERSION 4.5.3
Source code file: constr.c, line: 176
Fatal error:
Too many LINCS warnings (1009)
If you know what you are doing you can adjust the lincs warning threshold in your mdp file
or set the environment variable GMX_MAXCONSTRWARN to -1,
but normally it is better to fix the problem
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors**

Thanks,
Khushboo Singh
Ph.D. Candidate

**Comment by BerndDoser** [comment]
Dear Khushboo,

your issue seems to me belonging more to general GROMACS (please read http://www.gromacs.org/Documentation/Terminology/Blowing_Up) as to FDA. Could you please check a pure rerun without FDA. If the issue only occurs in FDA, please check if the GROMACS version generating the trajectory is identical to the GROMACS version you use for the FDA rerun (4.5.3).

You should think about an upgrade of GROMACS and FDA, as the version 4.5.3 is now six years old. FDA is now also available for v5.0 and v5.1 and very soon for v2016.

Best regrads,
Bernd

**Comment by KhushSingh** [comment]
Hi Bernd,

Thank you so much for your response. As mentioned by you the error was in the topology file and has nothing to do with FDA. However, now I am getting an error (pasted below), which I assume is specific to FDA.

**Program mdrun_pf2, VERSION 4.5.3
Source code file: pf_utils.c, line: 659
Fatal Error: When using compat mode, the two group names should the identical.**

I am assuming its related to the groups (pf_group 1 and pf_group2) mentioned in the .pfi file. The contents of my .pfi file are pasted below. I have atom indices for my Protein and 43B (ligand) in my index file. Also, the energygrps in my .mdp file (that is required to generate .tpr) mentions Protein and 43B. It would be of great help if you could guide me in the direction that could fix this issue. 

**; pf_onepair could be detailed or summed
pf_onepair = summed
; group1 and group2 as defined in the -pfn file; if not defined,
defaults to 'Protein'
pf_group1 = Protein
pf_group2 = 43B
; no interest in atom-based information
pf_atombased = no
; output residue-based information in compatibility format
pf_residuebased = compat_ascii
; interactions type could be one of more of:
; bond angle dihedral polar coulomb lj nb14 bonded nonbonded all
pf_type = all
pf_residuesrenumber = no
; scalar summation over all steps
pf_time_averages_period = 0**

Regards,
Khushboo Singh

**Comment by BerndDoser** [comment]
Dear Khushboo,

'pf_residuebased = compat_ascii' is a deprecated option to be compatible with the very first FDA implementation, where only one group was supported (see [manual](https://github.com/HITS-MBM/gromacs-fda/blob/release-5-1-fda2.7/fda-manual/fda-manual.pdf)). Therefore, the two group name must be identical, as the error message said.

Best regards,
Bernd

**Comment by KhushSingh** [comment]
Thank you for helping me. I was finally able to generate relevant output files. 

Regards,
Khushboo

**Comment by BerndDoser** [comment]
You're welcome!
