### ISSUE TITLE
typos in fda-manual.pdf

### ISSUE THREAD

**Issue by realsobek** [HITS-MBM/gromacs-fda#42]
In the manual https://github.com/HITS-MBM/gromacs-fda/blob/release-2020-fda/fda-manual/fda-manual.pdf I noticed some typing mistakes. Keep in mind I am not a native speaker and not an expert in the field. I could not compile a patch, because I could not find the source of the file. Hence, I created this issue.

At first you see the current spelling. Then a separator line. At the end of the separator line you might see "multi". This indicates that this particular item can be found multiple times in the document. After the separator line you see my suggested fix.
```
the gromacs version
--
the GROMACS version


numbers ar identical
--
numbers are identical


  -b <gromacs-version>-fda<fda-version>
--
  -b release-<version, usually year>-fda


1. building of an atom to residue correspondence table
--
1. building of an atom according to residue correspondence table


f.e.
-- multi
f.i.


F.e.
--
F.i.


contiguous
-- multi
continuous


representations !
--
representations!


forcefield
--
force field


indeces
-- multi
indices (or indexes)
```

**Comment by BerndDoser** [comment]
Thank you very much for your valuable references. I am currently working on the migration of the pdf document into the better maintainable markdown language and will gladly take your references into account.
